"use client";

import { useEffect, useState } from "react";
import { useTheme } from "next-themes";
import { toast } from "sonner";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Bell, ChevronDown, CircleHelp, LayoutDashboard, Moon, Plus, Search, Settings, Sun, Target, TrendingDown, TrendingUp, WalletCards, Tags, ChartNoAxesCombined, PiggyBank, ArrowUpRight, ArrowDownRight, Utensils, Car, House, Play, Menu, Lightbulb, BadgeCheck, ChartSpline } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { accounts as seedAccounts, budgets as seedBudgets, goals as seedGoals, monthlyData, transactions as seedTransactions } from "@/features/finance/data";
import { formatCurrency, savingRate, totalBalance, totalExpense, totalIncome } from "@/features/finance/calculations";
import { FeaturePage } from "@/features/app/feature-pages";
import { TransactionDialog } from "@/features/transactions/transaction-dialog";
import type { Account, Budget, Goal, Transaction } from "@/features/finance/types";

const nav = [
  ["Tổng quan", LayoutDashboard], ["Giao dịch", WalletCards], ["Ngân sách", PiggyBank], ["Tài khoản", WalletCards], ["Mục tiêu", Target], ["Báo cáo", ChartNoAxesCombined], ["Danh mục", Tags], ["Cài đặt", Settings],
] as const;

const icons: Record<string, React.ElementType> = { "Ăn uống": Utensils, "Di chuyển": Car, "Nhà ở": House, "Giải trí": Play };

export function Dashboard({ initialData }: { initialData?: { accounts: Account[]; transactions: Transaction[]; budgets: Budget[]; goals: Goal[] } }) {
  const { resolvedTheme, setTheme } = useTheme();
  const [range, setRange] = useState("6 tháng");
  const [active, setActive] = useState("Tổng quan");
  const [addOpen, setAddOpen] = useState(false);
  const [deleteId, setDeleteId] = useState<string | null>(null);
  const [globalSearch, setGlobalSearch] = useState("");
  const [transactions, setTransactions] = useState(initialData?.transactions ?? seedTransactions);
  const [accounts] = useState(initialData?.accounts ?? seedAccounts);
  const [budgets] = useState(initialData?.budgets ?? seedBudgets);
  const [goals, setGoals] = useState(initialData?.goals ?? seedGoals);
  const income = totalIncome(transactions), expense = totalExpense(transactions), saved = income - expense;
  useEffect(()=>{
    type Tool={name:string;title:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown};
    const context=(document as Document & {modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
    if(!context?.registerTool)return; const lifecycle=new AbortController();
    const register=(tool:Tool)=>void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>undefined);
    register({name:"read_financial_summary",title:"Xem tổng quan tài chính",description:"Đọc tổng thu nhập, chi tiêu và tiền tiết kiệm đang hiển thị trong Spendly.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({income,expense,savings:income-expense,currency:"VND"})});
    register({name:"create_transaction",title:"Thêm giao dịch",description:"Tạo một khoản thu hoặc chi mới trong Spendly.",inputSchema:{type:"object",properties:{type:{type:"string",enum:["income","expense"]},amount:{type:"number",minimum:1},description:{type:"string",minLength:2},category:{type:"string"},account:{type:"string"}},required:["type","amount","description","category","account"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input)=>{const value=input as Partial<Transaction>;if((value.type!=="income"&&value.type!=="expense")||!value.amount||!value.description||!value.category||!value.account)throw new Error("Dữ liệu giao dịch không hợp lệ");const item:Transaction={id:crypto.randomUUID(),type:value.type,amount:value.amount,description:value.description,category:value.category,account:value.account,date:new Date().toISOString(),color:value.type==="income"?"#22c55e":"#f59e0b",status:"completed"};const response=await fetch("/api/transactions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(item)});if(!response.ok)throw new Error("Không thể lưu giao dịch");setTransactions(items=>[item,...items]);return {id:item.id,status:"created",amount:item.amount,currency:"VND"}}});
    return()=>lifecycle.abort();
  },[income,expense]);
  async function persistTransaction(item: Transaction) { setTransactions(items=>[item,...items]); const response=await fetch("/api/transactions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(item)}); if(!response.ok)toast.error("Chưa thể đồng bộ giao dịch, vui lòng thử lại"); }
  async function removeTransaction(id: string) { const before=transactions; setTransactions(items=>items.filter(i=>i.id!==id)); const response=await fetch(`/api/transactions?id=${encodeURIComponent(id)}`,{method:"DELETE"}); if(!response.ok){setTransactions(before);toast.error("Không thể xóa giao dịch");return} toast.success("Đã xóa giao dịch"); }
  return <div className="min-h-screen bg-background text-foreground lg:grid lg:grid-cols-[252px_1fr]">
    <aside className="fixed inset-y-0 left-0 z-30 hidden w-[252px] flex-col bg-sidebar text-sidebar-foreground lg:flex">
      <div className="flex h-20 items-center gap-3 border-b border-sidebar-border px-7"><div className="grid size-9 place-items-center rounded-xl bg-blue-500 font-black text-white">S</div><span className="text-xl font-bold tracking-tight text-white">Spendly</span></div>
      <nav className="flex-1 space-y-1.5 px-4 py-6">{nav.map(([label, Icon]) => <button key={label} onClick={()=>setActive(label)} className={`flex h-11 w-full items-center gap-3 rounded-xl px-3 text-left text-sm font-medium transition ${active === label ? "bg-blue-500 text-white shadow-lg shadow-blue-950/20" : "hover:bg-sidebar-accent hover:text-white"}`}><Icon className="size-[18px]" />{label}</button>)}</nav>
      <div className="m-4 rounded-2xl border border-sidebar-border bg-sidebar-accent/60 p-4"><CircleHelp className="mb-3 size-5 text-blue-400"/><p className="text-sm font-semibold text-white">Cần hỗ trợ?</p><p className="mt-1 text-xs leading-5 text-slate-400">Khám phá hướng dẫn sử dụng Spendly.</p></div>
      <div className="flex items-center gap-3 border-t border-sidebar-border p-4"><div className="grid size-10 place-items-center rounded-full bg-blue-100 font-bold text-blue-700">AN</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-white">An Nguyễn</p><p className="truncate text-xs text-slate-400">an@spendly.app</p></div><ChevronDown className="size-4"/></div>
    </aside>
    <main className="min-w-0 lg:col-start-2">
      <header className="sticky top-0 z-20 flex h-20 items-center gap-3 border-b bg-card/90 px-4 backdrop-blur-xl sm:px-7">
        <Button variant="ghost" size="icon" className="lg:hidden" aria-label="Mở menu" onClick={()=>setActive("Cài đặt")}><Menu/></Button>
        <div className="relative hidden max-w-md flex-1 md:block"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={globalSearch} onChange={e=>setGlobalSearch(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")setActive("Giao dịch")}} className="h-10 bg-muted/70 pl-10" placeholder="Tìm giao dịch, tài khoản..."/></div>
        <div className="ml-auto flex items-center gap-2"><Button variant="outline" className="hidden gap-2 sm:flex" onClick={() => setRange(range === "6 tháng" ? "Tháng này" : "6 tháng")}>{range}<ChevronDown className="size-4"/></Button><Button variant="ghost" size="icon" aria-label="Đổi giao diện" onClick={() => setTheme(resolvedTheme === "dark" ? "light" : "dark")}>{resolvedTheme === "dark" ? <Sun/> : <Moon/>}</Button><Button variant="ghost" size="icon" className="relative" aria-label="Thông báo" onClick={()=>toast.info("Bạn đã dùng 85% ngân sách Giải trí")}><Bell/><span className="absolute right-2 top-2 size-2 rounded-full bg-rose-500 ring-2 ring-card"/></Button><Button className="gap-2 shadow-lg shadow-blue-500/20" onClick={()=>setAddOpen(true)}><Plus/>Thêm giao dịch</Button></div>
      </header>
      {active === "Tổng quan" ? <div className="mx-auto max-w-[1480px] space-y-6 p-4 pb-24 sm:p-7 lg:pb-8">
        <section className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-blue-600">Thứ Hai, 05 tháng 10</p><h1 className="mt-1 text-2xl font-bold tracking-tight sm:text-3xl">Chào buổi sáng, An</h1><p className="mt-1 text-sm text-muted-foreground">Đây là tình hình tài chính của bạn hôm nay.</p></div><p className="text-sm text-muted-foreground">Cập nhật vài giây trước</p></section>
        <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
          {[{label:"Tổng số dư",value:totalBalance(accounts),delta:"+8,2%",up:true,icon:WalletCards},{label:"Thu nhập tháng",value:income,delta:"+12,5%",up:true,icon:TrendingUp},{label:"Chi tiêu tháng",value:expense,delta:"−14,3%",up:true,icon:TrendingDown},{label:"Tiết kiệm",value:saved,delta:`${savingRate(transactions).toFixed(1)}%`,up:true,icon:PiggyBank}].map(({label,value,delta,up,icon:Icon})=><Card key={label} className="border-0 p-5 shadow-[0_1px_2px_rgba(16,24,40,.04),0_8px_24px_rgba(16,24,40,.05)]"><div className="flex items-start justify-between"><div className="grid size-10 place-items-center rounded-xl bg-blue-50 text-blue-600 dark:bg-blue-950"><Icon className="size-5"/></div><span className={`flex items-center text-xs font-semibold ${up?"text-emerald-600":"text-rose-600"}`}>{up?<ArrowUpRight className="size-3.5"/>:<ArrowDownRight className="size-3.5"/>}{delta}</span></div><p className="mt-5 text-sm text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-bold tracking-tight">{formatCurrency(value)}</p><p className="mt-1 text-xs text-muted-foreground">so với tháng trước</p></Card>)}
        </section>
        <section className="grid gap-6 xl:grid-cols-[minmax(0,1.55fr)_minmax(300px,.8fr)]">
          <Card className="border-0 p-5 shadow-[0_8px_30px_rgba(16,24,40,.05)]"><div className="mb-6 flex items-center justify-between"><div><h2 className="font-bold">Dòng tiền</h2><p className="text-sm text-muted-foreground">Thu nhập và chi tiêu theo tháng</p></div><div className="flex gap-4 text-xs"><span className="flex items-center gap-2"><i className="size-2 rounded-full bg-blue-500"/>Thu nhập</span><span className="flex items-center gap-2"><i className="size-2 rounded-full bg-rose-400"/>Chi tiêu</span></div></div><div className="h-[285px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={monthlyData} barGap={6}><CartesianGrid vertical={false} strokeDasharray="3 3" stroke="var(--border)"/><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fill:"var(--muted-foreground)",fontSize:12}}/><YAxis axisLine={false} tickLine={false} tick={{fill:"var(--muted-foreground)",fontSize:12}} tickFormatter={(v)=>`${v}tr`}/><Tooltip cursor={{fill:"var(--muted)"}} contentStyle={{borderRadius:12,border:"1px solid var(--border)",background:"var(--card)"}}/><Bar dataKey="income" fill="#2563eb" radius={[5,5,0,0]} maxBarSize={26}/><Bar dataKey="expense" fill="#fb7185" radius={[5,5,0,0]} maxBarSize={26}/></BarChart></ResponsiveContainer></div></Card>
          <Card className="border-0 p-5 shadow-[0_8px_30px_rgba(16,24,40,.05)]"><div className="flex items-center justify-between"><div><h2 className="font-bold">Ngân sách</h2><p className="text-sm text-muted-foreground">Tháng 10/2026</p></div><Button variant="ghost" size="sm" onClick={()=>setActive("Ngân sách")}>Xem tất cả</Button></div><div className="mt-6 space-y-6">{budgets.map((budget)=>{const pct=Math.round(budget.spent/budget.limit*100);const Icon=icons[budget.name]||PiggyBank;return <div key={budget.id}><div className="mb-2 flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl" style={{background:`${budget.color}18`,color:budget.color}}><Icon className="size-4.5"/></div><div className="min-w-0 flex-1"><div className="flex justify-between text-sm"><span className="font-semibold">{budget.name}</span><span className={pct>=80?"font-semibold text-amber-600":"font-semibold"}>{pct}%</span></div><p className="text-xs text-muted-foreground">{formatCurrency(budget.spent)} / {formatCurrency(budget.limit)}</p></div></div><Progress value={pct} className="h-1.5"/></div>})}</div></Card>
        </section>
        <section className="grid gap-4 md:grid-cols-3"><Card className="border-0 p-5 shadow-sm"><div className="flex items-start gap-3"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-amber-50 text-amber-600"><Lightbulb className="size-5"/></div><div><p className="text-xs font-bold uppercase tracking-wide text-amber-600">Insight</p><p className="mt-1 text-sm font-semibold leading-6">Chi tiêu ăn uống tháng này cao hơn tháng trước 18%.</p></div></div></Card><Card className="border-0 p-5 shadow-sm"><div className="flex items-start gap-3"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-violet-50 text-violet-600"><ChartSpline className="size-5"/></div><div><p className="text-xs font-bold uppercase tracking-wide text-violet-600">Dự báo</p><p className="mt-1 text-sm font-semibold leading-6">Bạn có thể đạt mục tiêu MacBook sớm hơn 2 tháng.</p></div></div></Card><Card className="border-0 p-5 shadow-sm"><div className="flex items-start gap-3"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-emerald-50 text-emerald-600"><BadgeCheck className="size-5"/></div><div><p className="text-xs font-bold uppercase tracking-wide text-emerald-600">Tích cực</p><p className="mt-1 text-sm font-semibold leading-6">Chi tiêu tháng này thấp hơn tháng trước 14,3%.</p></div></div></Card></section>
        <Card className="border-0 shadow-[0_8px_30px_rgba(16,24,40,.05)]"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-bold">Giao dịch gần đây</h2><p className="text-sm text-muted-foreground">6 giao dịch mới nhất</p></div><Button variant="outline" size="sm" onClick={()=>setActive("Giao dịch")}>Xem tất cả</Button></div><div className="divide-y">{transactions.slice(0,5).map((item)=>{const Icon=icons[item.category]||WalletCards;return <div key={item.id} className="flex items-center gap-3 px-5 py-3.5 hover:bg-muted/40"><div className="grid size-10 place-items-center rounded-xl" style={{background:`${item.color}18`,color:item.color}}><Icon className="size-[18px]"/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{item.description}</p><p className="text-xs text-muted-foreground">{item.category} · {item.account}</p></div><p className="hidden text-xs text-muted-foreground sm:block">{new Date(item.date).toLocaleDateString("vi-VN")}</p><p className={`min-w-[112px] text-right text-sm font-bold ${item.type==="income"?"text-emerald-600":""}`}>{item.type==="income"?"+":"−"}{formatCurrency(item.amount)}</p></div>})}</div></Card>
      </div> : <FeaturePage active={active} transactions={transactions} accounts={accounts} budgets={budgets} goals={goals} onAdd={()=>setAddOpen(true)} onDeleteTransaction={setDeleteId} onDuplicateTransaction={(item)=>{setTransactions(items=>[{...item,id:crypto.randomUUID(),description:`${item.description} (bản sao)`},...items]);toast.success("Đã nhân bản giao dịch")}} onAddGoalMoney={(id,amount)=>setGoals(items=>items.map(g=>g.id===id?{...g,saved:g.saved+amount}:g))}/>} 
      <nav className="fixed inset-x-0 bottom-0 z-40 grid h-16 grid-cols-5 border-t bg-card px-2 lg:hidden">{[["Tổng quan",LayoutDashboard],["Giao dịch",WalletCards],["",Plus],["Ngân sách",PiggyBank],["Cài đặt",Menu]].map(([label,Icon],i)=><button key={i} onClick={()=>i===2?setAddOpen(true):setActive(label as string)} className={`flex flex-col items-center justify-center gap-1 text-[11px] ${active===label?"text-blue-600":"text-muted-foreground"}`}>{i===2?<span className="-mt-7 grid size-12 place-items-center rounded-full bg-blue-600 text-white shadow-lg"><Plus/></span>:<><Icon className="size-5"/><span>{label as string}</span></>}</button>)}</nav>
    </main>
    <TransactionDialog open={addOpen} onOpenChange={setAddOpen} onSubmit={(item)=>void persistTransaction(item)}/>
    <AlertDialog open={!!deleteId} onOpenChange={(open)=>!open&&setDeleteId(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Xóa giao dịch?</AlertDialogTitle><AlertDialogDescription>Giao dịch sẽ bị xóa khỏi lịch sử và các báo cáo liên quan.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Hủy</AlertDialogCancel><AlertDialogAction onClick={()=>{if(deleteId)void removeTransaction(deleteId);setDeleteId(null)}}>Xóa giao dịch</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}
