"use client";

import { useState } from "react";
import { toast } from "sonner";
import { ArrowDownLeft, ArrowLeftRight, ArrowUpRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import type { Transaction, TransactionType } from "@/features/finance/types";

export function TransactionDialog({ open, onOpenChange, onSubmit }: { open: boolean; onOpenChange: (open:boolean)=>void; onSubmit: (item:Transaction)=>void }) {
  const [type,setType]=useState<TransactionType>("expense"); const [amount,setAmount]=useState(""); const [description,setDescription]=useState(""); const [category,setCategory]=useState("Ăn uống"); const [account,setAccount]=useState("Vietcombank"); const [note,setNote]=useState("");
  function save(){const parsed=Number(amount.replace(/\D/g,""));if(!parsed||parsed<=0){toast.error("Vui lòng nhập số tiền hợp lệ");return}if(description.trim().length<2){toast.error("Vui lòng nhập nội dung giao dịch");return}onSubmit({id:crypto.randomUUID(),type,amount:parsed,description:description.trim(),category:type==="transfer"?"Chuyển tiền":category,account,date:new Date().toISOString(),color:type==="income"?"#22c55e":type==="transfer"?"#2563eb":"#f59e0b",status:"completed"});setAmount("");setDescription("");setNote("");onOpenChange(false);toast.success("Đã thêm giao dịch");}
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[calc(100dvh-1rem)] overflow-y-auto p-4 sm:max-w-xl sm:p-6"><DialogHeader><DialogTitle>Thêm giao dịch</DialogTitle><DialogDescription>Ghi lại giao dịch mới chỉ trong vài thao tác.</DialogDescription></DialogHeader><div className="grid grid-cols-3 gap-2">{([{"id":"expense","label":"Chi tiêu","icon":ArrowUpRight},{"id":"income","label":"Thu nhập","icon":ArrowDownLeft},{"id":"transfer","label":"Chuyển tiền","icon":ArrowLeftRight}] as const).map(item=><button type="button" key={item.id} onClick={()=>setType(item.id)} className={`flex min-h-16 flex-col items-center gap-1.5 rounded-xl border p-2 text-xs font-semibold transition sm:p-3 sm:text-sm ${type===item.id?"border-blue-500 bg-blue-50 text-blue-700 dark:bg-blue-950":"hover:bg-muted"}`}><item.icon className="size-5"/>{item.label}</button>)}</div><div className="space-y-2"><Label htmlFor="amount">Số tiền</Label><div className="relative"><Input id="amount" value={amount} onChange={e=>setAmount(e.target.value)} className="h-12 pr-12 text-lg font-bold" inputMode="numeric" placeholder="0" autoFocus/><span className="absolute right-4 top-1/2 -translate-y-1/2 text-sm font-semibold text-muted-foreground">VND</span></div></div><div className="space-y-2"><Label htmlFor="description">Nội dung</Label><Input id="description" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Ví dụ: Highlands Coffee"/></div><div className="grid gap-4 sm:grid-cols-2"><label className="space-y-2 text-sm font-medium">Danh mục<Select value={category} onValueChange={setCategory} disabled={type==="transfer"}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{(type==="income"?["Lương","Thưởng","Freelance","Đầu tư"]:["Ăn uống","Di chuyển","Nhà ở","Mua sắm","Giải trí"]).map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></label><label className="space-y-2 text-sm font-medium">Tài khoản<Select value={account} onValueChange={setAccount}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{["Vietcombank","Ví tiền mặt","MoMo","Tiết kiệm"].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></label></div><div className="space-y-2"><Label htmlFor="note">Ghi chú</Label><Textarea id="note" value={note} onChange={e=>setNote(e.target.value)} placeholder="Tùy chọn" rows={2}/></div><DialogFooter showCloseButton><Button onClick={save}>Lưu giao dịch</Button></DialogFooter></DialogContent></Dialog>;
}
